### ISSUE TITLE
warning message when compiling

### ISSUE THREAD

**Issue by szymtor** [eryxcc/lois#1]
I get the following warning message when compiling LOIS using make:

> g++ -std=c++0x -O3 src/env.cpp -c -o obj/env.o
> src/env.cpp:20:11: warning: 'this' pointer cannot be null in well-defined C++
>       code; comparison may be assumed to always evaluate to false
>       [-Wtautological-undefined-compare]
>   else if(this == NULL) throw env_exception();
> 

I have a MacBook Pro (Retina, 13-inch, Late 2013), using Mac OS X 10.11.6 (15G1004), 

gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by eryxcc** [comment]
Thanks, should be fixed.
