### ISSUE TITLE
substitute not working for many types

### ISSUE THREAD

**Issue by chardetm** [eryxcc/lois#12]
I have an issue with `substitute` when trying to insert elements in a set. My set is declared in an equivalent way as this:
`lois::lsetof<Transition<lois::elem, lois::elem>> myset;`

My struct Transition is a simple representation of a nominal automaton transition:
```
template<class State, class Symbol>
struct Transition {
  Transition(const State& src_, const Symbol& symbol_, const State& tgt_) : edge{src_, tgt_}, symbol{symbol_} {}
  
  State& src() {return edge.first;}
  State& dst() {return edge.second;}
  Symbol& smb() {return symbol;}
  const State& src() const {return edge.first;}
  const State& dst() const {return edge.second;}
  const Symbol& smb() const {return symbol;}
  
  lois::lpair<State, State> edge;
  Symbol symbol;
};
```

When I try to add an element to `myset` (with operator `+=`) I get this:
```
/home/chardetm/stageM2/nominalcpp/lib/include/lois.h: In instantiation of ‘T lois::substitute(const T&, lois::vptr, lois::term&) [with T = Transition<lois::elem, lois::elem>; lois::vptr = std::shared_ptr<lois::Variable>]’:
/home/chardetm/stageM2/nominalcpp/lib/include/lois.h:1100:61:   required from ‘void lois::lsetof<T>::insert(T, lois::contextptr, lois::contextptr) [with T = Transition<lois::elem, lois::elem>; lois::contextptr = std::shared_ptr<lois::Context>]’
/home/chardetm/stageM2/nominalcpp/lib/include/lois.h:904:47:   required from ‘lois::lsetof<T>& lois::lsetof<T>::operator+=(const T&) [with T = Transition<lois::elem, lois::elem>]’
/home/chardetm/stageM2/nominalcpp/examples.hpp:82:97:   required from here
/home/chardetm/stageM2/nominalcpp/lib/include/lois.h:219:20: error: no matching function for call to ‘substitute(const Transition<lois::elem, lois::elem>&, lois::varsubstlist&)’
   return substitute(x, l);
```

So I went to see the code, the interesting part is in `lois.h` here:
```
term substitute(const term&, const varsubstlist&);
rbool substitute(const rbool& phi, const varsubstlist&);

template<class T> T substitute(const T& x, vptr var, term& val) {
  varsubstlist l(1, make_pair(var, val));
  return substitute(x, l);
  }
```

My concern here is that `substitute(x,var,val)` is declared as a template but `substitute(x,l)` is not and exists only for `term` and `rbool`. I tried to create a custom substitute function but it didn't work, here is my attempt:
```
template<class State, class Symbol>
Transition<State,Symbol> substitute(const Transition<State,Symbol>& tthis, const lois::varsubstlist& l) {
  return {
    lois::substitute(tthis.src(), l),
    lois::substitute(tthis.smb(), l),
    lois::substitute(tthis.dst(), l)
  };
}
```
But `substitute` is not declared for `lois::elem` either.

Is there a good way to solve this problem that I missed? Thanks in advance!

**Comment by eryxcc** [comment]
`substitute` is declared for `lois::elem` (line 97 of lois-weak.h). My own implementation of this (see lois-automaton.h, line 22) is roughly the same. I guess that the template cannot find your `substitute` because it is declared outside of the `lois` namespace?

**Comment by chardetm** [comment]
Including `lois-weak.h` in my `transition.h` file (where my version of substitute is defined) fixed the problem, it seems strange to me that it couldn't find it in the first place as it knew the type lois::elem... Anyway, problem solved, thanks!
