### ISSUE TITLE
for loop over lsetof

### ISSUE THREAD

**Issue by szymtor** [eryxcc/lois#7]
The following code results in an error:

```
Domain dA("Atoms");
lset A = dA.getSet();

lsetof<elem> X = SETOF (a, a:A, true);  
for (auto x: X) {}
```
The error says:
```
libc++abi.dylib: terminating with uncaught exception of type lois::as_exception: LOIS exception
Abort trap: 6
```

Replacing `lsetof<elem>` by `lset` makes it work, but I would like to use sets with type checking (with more complicated types than elem).

**Comment by eryxcc** [comment]
[not checked]
Your code should work with lsetof<term>. What happens here is that "lsetof" wants a specific type of "elem" as a parameter, and the specific type of elements in your sets in "term" -- "elem" is not a specific type of "elem".

**Comment by szymtor** [comment]
Actually, in my situation, I want to have 
`lsetof<lpair<elem,lset>>`
and loop through this set with automatic type checking. How can I obtain this?
Also these programs results in an error:

```
  lsetof<lpair<term,term>> X = SETOF (elpair({a,a}), a:A, true);  
  for (auto x: X) {cout << x << endl;}
```

or 

```
  lsetof<lpair<elem,elem>> X = SETOF (elpair(a,a), a:A, true);  
  for (auto x: X) {cout << x << endl;}
```

(I know there is `elpair` but what if I want `lsetof<lpair<elem,lset>>`?)

**Comment by eryxcc** [comment]
Types lpair and elpair are different and thus they are not interchangeable (also lset and lsetof are different types) -- maybe SETOF (lpair<term,term>(a,a), a:A, true) in the first example would work?

(the learning example uses `lsetof<lpair<elpair, word>>` so it should work)

**Comment by szymtor** [comment]
This is what worked for `lsetof<lpair<elem,elem>>`:

```
lsetof<lpair<elem,elem>> X = SETOF (make_lpair(a,a), a:A, true);
for (auto x: X) 
  {cout << x.first << "," << x.second << endl;}
```

However, if I try   `lsetof<lpair<elem,lset>>` like this:

```
lsetof<lpair<elem,lset>> X = SETOF (make_lpair(a,newSet(a)), a:A, true);
```

then it doesn't compile, saying  

```
error: no viable conversion from returned
      value of type 'lpair<[...], lois::elem>' to function return type
      'lpair<[...], lois::lset>'
```

The same happens when compiling this code:

```
lsetof<lpair<elem,lset>> X = newSet();
for (auto a:A)
    X += make_lpair(a,newSet(a));  
```

**Comment by eryxcc** [comment]
Well, lpair<X,Y> are different types for different values of (X,Y) (and it is unable to cast) -- I guess that make_lpair has guessed the types incorrectly for some reason. Giving specific types (lpair<elem,lset> instead of make_lpair) should be fine?

**Comment by szymtor** [comment]
I've tried that – doesn't compile, with error:

```
tests/../include/loisextra.h:379:10: error: no viable conversion from returned
      value of type 'lpair<[...], lois::elem>' to function return type
      'lpair<[...], lois::lset>'
  return make_lpair(alpha(p.first, v1, v2), alpha(p.second, v1, v2));
```

I am guessing that `alpha` is not implemented for lset in particular, only for elem?
I've tried adding the following code to loisextra.h:

```
inline lset alpha(lset t, vptr v1, vptr v2) {
  lset v; for(elem e:t) v+= alpha(e, v1, v2); return v;
}
```

Then everything compiles, but executing the program writes a message "quick move used", so I'm not sure I did the right thing.

**Comment by eryxcc** [comment]
The message "Quick move used" should not be a problem -- a debug message that was not removed.

I thinkt that something like `return asSet(elem(t).alph(v1,v2))` should work as the implemntation of `inline lset alpha(lset t, vptr v1, vptr v2)`.

**Comment by szymtor** [comment]
Done! Now commit e9f820b adds the alpha for type lset, and the following program now works:

```
lsetof<lpair<elem,lset>> X = SETOF(make_lpair(a,newSet(a)),a:A, true);
for (auto x: X) 
  cout << x.first << "," << x.second << endl;
```

Thanks a lot!
